/*************************************************
* ESP8266 SSID CONNECT FRAMEWORK
*
* AUGUST 13 2016
*
* ANKIT BHATNAGAR
* ANKIT.BHATNAGARINDIA@GMAIL.COM
************************************************/

#ifndef _ESP8266_SSID_FRAMEWORK_H_
#define _ESP8266_SSID_FRAMEWORK_H_

#include "ets_sys.h"
#include "osapi.h"
#include "gpio.h"
#include "os_type.h"
#include "user_interface.h"
#include "ESP8266_GPIO.h"
#include "ESP8266_MDNS.h"
#include "ESP8266_SMARTCONFIG.h"

#if defined(SSID_HARDCODED)
#elif defined(SSID_FLASH)
  #include "ESP8266_FLASH.h"
#elif defined(SSID_EEPROM)
  #include "ESP8266_EEPROM_AT24.h"
#elif defined(SSID_INTERNAL)
#elif defined(SSID_GPIO)
#endif

#define ESP8266_FLASH_MAX_ADDRESS               0x400000
#define ESP8266_FLASH_ESP_BLANK_BIN_ADDRESS     0x3FE000
#define ESP8266_FLASH_ESP_INIT_BIN_ADDRESS      0x3FC000
#define ESP8266_FLASH_ESP_IROM0TEX_BIN_ADDRESS  0x10000

//CUSTOM VARIABLE STRUCTURES/////////////////////////////
typedef enum
{
	ESP8266_SSID_FRAMEWORK_SSID_INPUT_HARDCODED = 0,
  ESP8266_SSID_FRAMEWORK_SSID_INPUT_FLASH,
  ESP8266_SSID_FRAMEWORK_SSID_INPUT_EEPROM,
  ESP8266_SSID_FRAMEWORK_SSID_INPUT_INTERNAL,
  ESP8266_SSID_FRAMEWORK_SSID_INPUT_GPIO
}ESP8266_SSID_FRAMEWORK_SSID_INPUT_MODE;

typedef enum
{
	ESP8266_SSID_FRAMEWORK_CONFIG_SMARTCONFIG = 0,
  ESP8266_SSID_FRAMEWORK_CONFIG_WEBCONFIG
}ESP8266_SSID_FRAMEWORK_CONFIG_MODE;
//END CUSTOM VARIABLE STRUCTURES/////////////////////////

//FUNCTION PROTOTYPES/////////////////////////////////////////////
//CONFIGURATION FUNCTIONS
void ICACHE_FLASH_ATTR ESP8266_SSID_FRAMEWORK_SetDebug(uint8_t debug);
void ICACHE_FLASH_ATTR ESP8266_SSID_FRAMEWORK_SetParameters(ESP8266_SSID_FRAMEWORK_SSID_INPUT_MODE input_mode, ESP8266_SSID_FRAMEWORK_CONFIG_MODE config_mode, void* user_data);

//OPERATION FUNCTIONS


//INTERNAL FUNCTIONS

#endif
